<a href="https://colab.research.google.com/github/davidmkidd/UK-Supermarket-Carbon-Emissions/blob/main/UKSmktComp_Stores_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://evoviz.uk/wp-content/uploads/2026/04/Food_Divider_trans2.png">

# Clean Geolytix Retailer Points

Emissions and energy use are expected increases with business 'size'. In this second Workbook, the the Geolytix Retail Points dataset is cleaned and summarised ready for graphical explortation. Data is imported and manipulated using a combination of basic R functions and functions from external libraries, *dpylr* and *tidyr*. Code syntax is explained when first used.

# Set-up

Workbooks begin with a 'set-up' section that loads required R libraries and data.


## Load Libraries
Libraries provide additional 'specialist' functionality not supported by the 'base' program. Colab provides some commonly used libraries as 'ready-to-import' packages loaded with the *library()* function.

* [dpylr](https://dplyr.tidyverse.org/) is data manipulation library.
* [tidyr](https://tidyr.tidyverse.org/) manages ta

In [ ]:
library(dplyr)
library(tidyr)

## Download and Import Data
The next step is to import the Geolytix Retail Points dataset from the Github repository where it is stored to the /content folder.

In [ ]:
# Store the address of the csv file in a variable named 'url'
url <- "https://raw.githubusercontent.com/davidmkidd/UK-Supermarket-Carbon-Emissions/refs/heads/main/geolytix_retailpoints_v34_202412.csv"

# Store the path in Colab where the file will be saved to
download_path <- "/content/geolytix_retailpoints_v34_202412.csv"

# Download the file to the destination
download.file(url, destfile = download_path, mode = "wb")

#Import the CSV file to a variable named 'store'
store <- read.csv("/content/geolytix_retailpoints_v34_202412.csv", header=TRUE, stringsAsFactors=FALSE)

That is all the set-up required for this workbook.

# Data Frame

*read.csv()* imports data in CSV formatted text file into an R *data frame*. CSV and the R data frame are both 'table' formats in which data is stored as attribute columns and record rows. Let's explore the 'store' data frame.

In [ ]:
# ncol() returns the number of data frame columns
ncol(store)

[1] 19

In [ ]:
# names() and colnames() returns a vector of column names
names(store)

 [1] "id"         "retailer"   "fascia"     "store_name" "add_one"
 [6] "add_two"    "town"       "suburb"     "postcode"   "long_wgs"
[11] "lat_wgs"    "bng_e"      "bng_n"      "pqi"        "open_date"
[16] "size_band"  "county"     "year"       "size_level"

Items in a vector are accessed via their position index []

In [ ]:
# First item
names(store)[1]

# Items 4 to 8
names(store)[4:8]

# Without the third item
names(store)[-3]

[1] "id"

[1] "store_name" "add_one"    "add_two"    "town"       "suburb"

 [1] "id"         "retailer"   "store_name" "add_one"    "add_two"
 [6] "town"       "suburb"     "postcode"   "long_wgs"   "lat_wgs"
[11] "bng_e"      "bng_n"      "pqi"        "open_date"  "size_band"
[16] "county"     "year"       "size_level"

In [ ]:
# nrow() returns the number of data frame records
# Each row is a store
nrow(store)

[1] 18840

In [ ]:
# summary() returns a summary report of columns and their contents
summary(store)

       id             retailer            fascia           store_name
 Min.   :1.01e+09   Length:18840       Length:18840       Length:18840
 1st Qu.:1.01e+09   Class :character   Class :character   Class :character
 Median :1.01e+09   Mode  :character   Mode  :character   Mode  :character
 Mean   :1.01e+09
 3rd Qu.:1.01e+09
 Max.   :1.01e+09

   add_one            add_two              town              suburb
 Length:18840       Length:18840       Length:18840       Length:18840
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character




   postcode            long_wgs          lat_wgs          bng_e
 Length:18840       Min.   :-8.0899   Min.   :49.17   Min.   :  5123
 Class :character   1st Qu.:-2.8045   1st Qu.:51.50   1st Qu.:346908
 Mode  :character   Median :-1.5874   Median :52.50   Median :427048
                    Mean   :-1.7833   Mean   :52.81   Mean   :416710
                    3rd Qu.:-0.4016   3rd Qu.:53.71   3rd Qu.:509612
                    Max.   : 1.7529   Max.   :60.40   Max.   :654949

     bng_n             pqi              open_date         size_band
 Min.   : -81178   Length:18840       Min.   :18559999   Length:18840
 1st Qu.: 179310   Class :character   1st Qu.:20179999   Class :character
 Median : 290230   Mode  :character   Median :20210916   Mode  :character
 Mean   : 324690                      Mean   :20206981
 3rd Qu.: 424197                      3rd Qu.:20231025
 Max.   :1168234                      Max.   :20249999
                                      NA's   :12763
    county               year         size_level
 Length:18840       Min.   :   1    Min.   :1.000
 Class :character   1st Qu.:2017    1st Qu.:1.000
 Mode  :character   Median :2021    Median :1.000
                    Mean   :2020    Mean   :1.605
                    3rd Qu.:2023    3rd Qu.:2.000
                    Max.   :2024    Max.   :5.000
                    NA's   :12763   NA's   :1

In [ ]:
# Typing the name of a data frame returns a default number of rows.
store

      id         retailer                 fascia
1     1010008812 The Co-operative Group   The Co-operative Food
2     1010021060 Spar                     Spar
3     1010007877 The Co-operative Group   The Co-operative Food
4     1010016823 Spar                     Spar
5     1010010459 Tesco                    Tesco
6     1010007420 Lidl                     Lidl
7     1010004399 Tesco                    Tesco
8     1010022270 Morrisons                Morrisons Daily
9     1010017041 Spar                     Spar
10    1010016321 Spar                     Spar
11    1010017115 Spar                     Spar
12    1010016284 Spar                     Spar
13    1010016240 Spar                     Spar
14    1010015136 Aldi                     Aldi
15    1010015546 Aldi                     Aldi
16    1010016291 Spar                     Spar
17    1010016795 Spar                     Spar
18    1010017105 Spar                     Spar
19    1010020949 Morrisons                Morrisons Daily
20    1010014428 Aldi                     Aldi
21    1010017123 Spar                     Spar
22    1010016268 Spar                     Spar
23    1010016335 Spar                     Spar
24    1010009411 The Co-operative Group   The Co-operative Food
25    1010015217 Budgens                  Budgens
26    1010007361 Lidl                     Lidl
27    1010005577 Tesco                    Tesco Express
28    1010008520 The Co-operative Group   The Co-operative Food
29    1010003790 Sainsburys               Sainsburys Local
30    1010005573 Tesco                    Tesco Express
⋮     ⋮          ⋮                        ⋮
18811 1010007269 Lidl                     Lidl
18812 1010019587 Lidl                     Lidl
18813 1010021978 Cook                     Cook
18814 1010016851 Spar                     Spar
18815 1010019950 Spar                     Spar
18816 1010017218 Spar                     Spar
18817 1010013054 Farmfoods                Farmfoods
18818 1010019773 Spar                     Spar
18819 1010020377 Budgens                  Budgens
18820 1010008472 The Co-operative Group   The Co-operative Food
18821 1010014988 The Co-operative Group   The Co-operative Food
18822 1010018462 Spar                     Spar
18823 1010010972 Iceland                  Iceland
18824 1010011022 Iceland                  Iceland
18825 1010000378 Aldi                     Aldi
18826 1010004316 Tesco                    Tesco
18827 1010002963 Sainsburys               Sainsburys
18828 1010012576 Midcounties Co-operative The Co-operative Food
18829 1010019027 Morrisons                Morrisons Daily
18830 1010001924 Marks and Spencer        Marks and Spencer Simply Food
18831 1010013970 Lidl                     Lidl
18832 1010016505 Spar                     Spar
18833 1010017006 Spar                     Spar
18834 1010017969 Spar                     Spar
18835 1010017119 Spar                     Spar
18836 1010007793 The Co-operative Group   The Co-operative Food
18837 1010021975 Cook                     Cook
18838 1010007999 The Co-operative Group   The Co-operative Food
18839 1010021061 Spar                     Spar
18840 1010014305 Iceland                  Iceland
      store_name
1     Co-op Holyhead Road - Chirk
2     Spar Glyn Ceiriog
3     Co-op Blaenau Ffestiniog
4     Spar - Cynwyd Post Office & General Store
5     Tesco Wrexham Superstore
6     Lidl Newtown
7     Tesco Welshpool Superstore
8     Morrisons Daily Welshpool
9     Spar - Llanrheadr
10    Spar - Montgomery
11    Spar - Llanfair Caereinion
12    Spar - Chirk
13    Spar - Glyn Ceiriog
14    Aldi Llangollen
15    Aldi Watkin Way
16    Spar - Eurospar Dolgellau
17    Spar - Dolgellau
18    Spar - Dolgellau
19    Morrisons Blaenau Ffestiniog Church
20    Aldi Welshpool
21    Spar - Carno
22    Spar - Llansantffraid
23    Spar - Llanfyllin
24    Co-op Clydach
25    Budgens Cockett Swansea
26    Lidl Trallwn Swansea
27    Tesco Sketty Gower Rd Express
28    Co-op Swansea - Mumbles Road
29    Sainsburys Swansea Uplands Crescent Local
30    Tesco Swansea De La Beche St Express
⋮     ⋮
18811 Lidl Caister-on-Sea
18812 Lidl Hexham
18813 Cook Hove
18814 Spar - Tremadog
18815 Spar Longhedge
18816 Spar - Bethel
18817 Farmfoods Stockton
18818 Spar Cricklade
18819 Budgens Newby Bridge
18820 Co-op Askam
18821 Co-op Paisley Road - Renfrew
18822 Spar - Renfrew
18823 Iceland Paisley
18824 Iceland Paisley Piazza
18825 Aldi Erskine
18826 Tesco Paisley Superstore
18827 Sainsburys Braehead
18828 Co-op Shawbury
18829 Morrisons Daily Shrewsbury
18830 M&S Maldon SF
18831 Lidl Heybridge
18832 Spar - Dursley
18833 Spar - Horn Lane Acton
18834 Spar - Hollinwood
18835 Spar - Bushey
18836 Co-op Sonning Common
18837 Cook Henley-on-Thames
18838 Co-op Didcot
18839 Spar Wantage
18840 Iceland Didcot
      add_one                            add_two
1     Holyhead Road                      Chirk
2     Cross Stores High Street
3     High Street                        Blaenau Ffestiniog
4     Cynwyd Post Office & General Store Station Road
5     Plas Kynaston Lane                 Off Well Street
6     Llanidloes Road
7     Smithfield Road
8     Buttington Cross Enterprise Park
9     The Market Square                  Oswestry
10    Broad Street
11    Llanfair Caereinion                Welshpool
12    16 Church Street
13    High Street
14    Berwyn Street
15    Watkin Way
16    Bala Road
17    Bala Road
18    Plas Yn Dref Street
19    39-41 Church Street                Blaenau Ffestiniog
20    Mill Lane
21    The Old Village Hall
22    Eagle House                        Llansantffraid
23    High Street
24    High Street                        Clydach
25    270 Cockett Road
26    Trallwn Road
27    37 Gower Road                      Sketty
28    Mumbles Road                       Mumbles
29    41 Uplands Crescent
30    11-12 De La Beche Street
⋮     ⋮                                  ⋮
18811 Norwich Road
18812 Alemouth Road
18813 38 Church Road Hove
18814 Market Square
18815 4 Rhodes Moorhouse Way
18816 Bethel
18817 3 Bath Lane
18818 16 White Horse Road
18819 A590 Newby Bridge
18820 Duke Street
18821 93 Paisley Road
18822 194-198 Paisley Road
18823 68-74 Glasgow Road
18824 Unit 55 The Piazza Shopping Centre
18825 1a Bridgewater Shopping Centre
18826 East Lane
18827 1 Braehead Retail Park             Kings Inch Road
18828 Market Drayton Road
18829 63 New Park Street
18830 40 40A 42 High Street
18831 Station Road
18832 Mill Garage                        Cam
18833 162-164 Horn Lane
18834 Hollins Rd
18835 90 High Street
18836 44 Wood Lane                       Sonning Common
18837 1 Oxford House
18838 202 Broadway
18839 18 Wallingford Street
18840 3-5 Market Place
      town                      suburb             postcode long_wgs   lat_wgs
1     Chirk                                        LL14 5NA -3.058428  52.94037
2     Glyn Ceiriog                                 LL20 7EH -3.188270  52.93246
3     Blaenau Ffestiniog        Blaenau Ffestiniog LL41 3AG -3.934357  52.99474
4     Cynwyd                                       LL21 0LA -3.405960  52.95915
5     Cefn-Mawr                                    LL14 3AT -3.070395  52.97315
6     Newtown, Powys                               SY16 1ET -3.319253  52.51006
7     Welshpool                                    SY21 7BL -3.141287  52.65868
8     Buttington                                   SY21 8SL -3.123082  52.67150
9     Llanrhaeadr-ym-Mochnant                      SY10 0JG -3.301328  52.82526
10    Montgomery                                   SY15 6PN -3.148419  52.56043
11    Llanfair Caereinion                          SY21 0AT -3.323949  52.64844
12    Chirk                                        LL14 5HA -3.056672  52.93183
13    Glyn Ceiriog                                 LL20 7EH -3.188873  52.93170
14    Llangollen                                   LL20 8BF -3.178164  52.97191
15    Ruabon                                       LL14 6EP -3.046569  52.98387
16    Dolgellau                                    LL40 2YF -3.879266  52.74590
17    Dolgellau                                    LL40 2YE -3.881202  52.74588
18    Dolgellau                                    LL40 1BB -3.885399  52.74322
19    Blaenau Ffestiniog        Blaenau Ffestiniog LL41 3HD -3.937644  52.99537
20    Welshpool                                    SY21 7BL -3.142761  52.65972
21    Carno                                        SY17 5LH -3.536456  52.56007
22    Llansantffraid ym Mechain                    SY22 6AQ -3.153208  52.77438
23    Llanfyllin                                   SY22 5AA -3.274587  52.76732
24    Clydach, West Glamorgan                      SA6 5LJ  -3.893943  51.69488
25    Swansea                   Cockett            SA2 0FN  -3.983419  51.63509
26    Swansea                   Trallwn            SA7 9WL  -3.891868  51.65190
27    Swansea                   Sketty             SA2 9BX  -3.985840  51.61793
28    Mumbles                                      SA3 4DN  -3.997735  51.57464
29    Swansea                   Central Swansea    SA2 0NP  -3.965885  51.61794
30    Swansea                   Central Swansea    SA1 3EZ  -3.946967  51.62194
⋮     ⋮                         ⋮                  ⋮        ⋮          ⋮
18811 Caister-on-Sea                               NR30 5JL  1.7242527 52.64851
18812 Hexham                                       NE46 3PD -2.0972744 54.97403
18813 Hove                      Central Hove       BN3 2FN  -0.1677317 50.82719
18814 Tremadog                                     LL49 9RB -4.1411982 52.93926
18815 Old Sarum                                    SP4 6SA  -1.7934974 51.10649
18816 St Austell                Mount Charles      PL25 3DW -4.7645400 50.34458
18817 Stockton                  Central Stockton   TS18 2DS -1.3080035 54.56806
18818 Cricklade                                    SN6 6EN  -1.8617700 51.64207
18819 Newby Bridge                                 LA12 8ND -2.9609758 54.26256
18820 Askam-in-Furness                             LA16 7AA -3.2050251 54.18852
18821 Renfrew                                      PA4 8LH  -4.3973899 55.87204
18822 Renfrew                                      PA4 8DS  -4.4006829 55.86896
18823 Paisley                   Central Paisley    PA1 3PN  -4.4064646 55.84651
18824 Paisley                   Central Paisley    PA1 1EH  -4.4223688 55.84650
18825 Erskine                   Erskine            PA8 7AA  -4.4490426 55.90432
18826 Paisley                   Central Paisley    PA1 1QA  -4.4039981 55.84593
18827 Renfrew                                      G51 4BP  -4.3569805 55.87273
18828 Shawbury, Shropshire                         SY4 4NZ  -2.6552711 52.78740
18829 Shrewsbury                Central Shrewsbury SY1 2LE  -2.7436981 52.71487
18830 Maldon                                       CM9 5PN   0.6771829 51.73124
18831 Maldon                                       CM9 4LQ   0.6801443 51.73513
18832 Dursley                   Lower Cam          GL11 5DH -2.3655430 51.70985
18833 London                    Acton              W3 6PH   -0.2682695 51.51487
18834 Oldham                    Werneth            OL8 4EH  -2.1230906 53.52315
18835 Bushey                                       WD23 3HD -0.3649164 51.64473
18836 Sonning Common                               RG4 9SL  -0.9815925 51.51740
18837 Henley-on-Thames                             RG9 1UR  -0.9036755 51.53636
18838 Didcot                    South Didcot       OX11 8RN -1.2440674 51.60659
18839 Wantage                   Wantage            OX12 8AX -1.4245000 51.58831
18840 Didcot                    South Didcot       OX11 7LE -1.2415885 51.60649
      bng_e    bng_n    pqi     open_date
1     328966.9 338632.9 Rooftop       NA
2     320226.8 337889.8 Rooftop 20230499
3     270269.0 345908.0 Rooftop       NA
4     305653.5 341122.8 Rooftop       NA
5     328217.1 342292.0 Rooftop       NA
6     310562.0 291058.9 Rooftop       NA
7     322901.3 307385.1 Rooftop       NA
8     324154.9 308791.7 Rooftop 20249999
9     312411.8 326097.0 Rooftop       NA
10    322244.8 296463.2 Rooftop       NA
11    310525.8 306456.5 Rooftop       NA
12    329070.9 337681.2 Rooftop       NA
13    320184.8 337805.6 Rooftop       NA
14    320978.1 342267.1 Rooftop 20170713
15    329834.4 343460.2 Rooftop 20190905
16    273242.0 318132.0 Rooftop       NA
17    273111.3 318133.6 Rooftop       NA
18    272820.2 317844.5 Rooftop       NA
19    270050.3 345983.6 Rooftop 20230299
20    322803.5 307501.9 Rooftop 20170499
21    295940.1 296913.3 Rooftop       NA
22    322301.2 320267.4 Rooftop       NA
23    314099.3 319620.4 Rooftop       NA
24    269196.0 201268.0 Rooftop       NA
25    262831.8 194783.7 Rooftop 20179999
26    269215.6 196485.3 Rooftop       NA
27    262612.4 192880.4 Rooftop       NA
28    261657.3 188089.1 Rooftop       NA
29    263993.8 192844.3 Rooftop       NA
30    265315.3 193254.2 Rooftop       NA
⋮     ⋮        ⋮        ⋮       ⋮
18811 652018.8 312153.2 Rooftop       NA
18812 393871.3 564384.0 Rooftop 20220331
18813 529142.2 104672.0 Rooftop       NA
18814 256203.9 340132.0 Rooftop       NA
18815 414553.9 134152.8 Rooftop       NA
18816 203397.7  53062.1 Rooftop       NA
18817 444839.1 519424.3 Rooftop       NA
18818 409662.0 193705.5 Rooftop       NA
18819 337502.4 485637.2 Rooftop 20220999
18820 321465.7 477642.7 Rooftop       NA
18821 250096.5 666918.1 Rooftop 20189999
18822 249878.7 666582.6 Rooftop       NA
18823 249430.1 664097.4 Rooftop       NA
18824 248434.5 664130.4 Rooftop       NA
18825 246992.6 670622.4 Rooftop       NA
18826 249582.2 664027.7 Rooftop       NA
18827 252627.0 666908.0 Rooftop       NA
18828 355904.9 321293.6 Rooftop       NA
18829 349858.0 313282.7 Rooftop 20210499
18830 584975.2 207005.7 Rooftop       NA
18831 585163.8 207445.9 Rooftop 20161299
18832 374839.4 201298.7 Rooftop       NA
18833 520261.1 180970.8 Rooftop       NA
18834 391936.7 402949.6 Rooftop       NA
18835 513232.3 195258.3 Rooftop       NA
18836 470761.4 180322.2 Rooftop       NA
18837 476136.2 182508.9 Rooftop       NA
18838 452446.7 190021.2 Rooftop       NA
18839 439967.5 187874.2 Rooftop 20230499
18840 452618.5 190011.8 Rooftop       NA
      size_band                              county             year size_level
1     < 3,013 ft2 (280m2)                    Clywd                NA 1
2     < 3,013 ft2 (280m2)                    Clywd              2023 1
3     3,013 < 15,069 ft2 (280 < 1,400 m2)    Gwynedd              NA 2
4     < 3,013 ft2 (280m2)                    Clywd                NA 1
5     15,069 < 30,138 ft2 (1,400 < 2,800 m2) Clywd                NA 3
6     3,013 < 15,069 ft2 (280 < 1,400 m2)    Powys                NA 2
7     15,069 < 30,138 ft2 (1,400 < 2,800 m2) Powys                NA 3
8     < 3,013 ft2 (280m2)                    Powys              2024 1
9     < 3,013 ft2 (280m2)                    Powys                NA 1
10    < 3,013 ft2 (280m2)                    Powys                NA 1
11    < 3,013 ft2 (280m2)                    Powys                NA 1
12    < 3,013 ft2 (280m2)                    Clywd                NA 1
13    < 3,013 ft2 (280m2)                    Clywd                NA 1
14    3,013 < 15,069 ft2 (280 < 1,400 m2)    Clywd              2017 2
15    3,013 < 15,069 ft2 (280 < 1,400 m2)    Clywd              2019 2
16    < 3,013 ft2 (280m2)                    Gwynedd              NA 1
17    < 3,013 ft2 (280m2)                    Gwynedd              NA 1
18    < 3,013 ft2 (280m2)                    Gwynedd              NA 1
19    < 3,013 ft2 (280m2)                    Gwynedd            2023 1
20    3,013 < 15,069 ft2 (280 < 1,400 m2)    Powys              2017 2
21    < 3,013 ft2 (280m2)                    Powys                NA 1
22    < 3,013 ft2 (280m2)                    Powys                NA 1
23    < 3,013 ft2 (280m2)                    Powys                NA 1
24    3,013 < 15,069 ft2 (280 < 1,400 m2)    West Glamorgan       NA 2
25    < 3,013 ft2 (280m2)                    West Glamorgan     2017 1
26    3,013 < 15,069 ft2 (280 < 1,400 m2)    West Glamorgan       NA 2
27    < 3,013 ft2 (280m2)                    West Glamorgan       NA 1
28    < 3,013 ft2 (280m2)                    West Glamorgan       NA 1
29    < 3,013 ft2 (280m2)                    West Glamorgan       NA 1
30    < 3,013 ft2 (280m2)                    West Glamorgan       NA 1
⋮     ⋮                                      ⋮                  ⋮    ⋮
18811 3,013 < 15,069 ft2 (280 < 1,400 m2)    Norfolk              NA 2
18812 3,013 < 15,069 ft2 (280 < 1,400 m2)    Northumberland     2022 2
18813 < 3,013 ft2 (280m2)                    East Sussex          NA 1
18814 < 3,013 ft2 (280m2)                    Gwynedd              NA 1
18815 < 3,013 ft2 (280m2)                    Wiltshire            NA 1
18816 < 3,013 ft2 (280m2)                    Cornwall             NA 1
18817 < 3,013 ft2 (280m2)                    County Durham        NA 1
18818 < 3,013 ft2 (280m2)                    Wiltshire            NA 1
18819 < 3,013 ft2 (280m2)                    Cumbria            2022 1
18820 < 3,013 ft2 (280m2)                    Cumbria              NA 1
18821 < 3,013 ft2 (280m2)                    Renfrewshire       2018 1
18822 < 3,013 ft2 (280m2)                    Renfrewshire         NA 1
18823 3,013 < 15,069 ft2 (280 < 1,400 m2)    Renfrewshire         NA 2
18824 3,013 < 15,069 ft2 (280 < 1,400 m2)    Renfrewshire         NA 2
18825 3,013 < 15,069 ft2 (280 < 1,400 m2)    Renfrewshire         NA 2
18826 15,069 < 30,138 ft2 (1,400 < 2,800 m2) Renfrewshire         NA 3
18827 30,138 ft2 > (2,800 m2)                Renfrewshire         NA 4
18828 < 3,013 ft2 (280m2)                    Shropshire           NA 1
18829 < 3,013 ft2 (280m2)                    Shropshire         2021 1
18830 3,013 < 15,069 ft2 (280 < 1,400 m2)    Essex                NA 2
18831 3,013 < 15,069 ft2 (280 < 1,400 m2)    Essex              2016 2
18832 < 3,013 ft2 (280m2)                    Gloucestershire      NA 1
18833 < 3,013 ft2 (280m2)                    Greater London       NA 1
18834 < 3,013 ft2 (280m2)                    Greater Manchester   NA 1
18835 < 3,013 ft2 (280m2)                    Hertfordshire        NA 1
18836 < 3,013 ft2 (280m2)                    Oxfordshire          NA 1
18837 < 3,013 ft2 (280m2)                    Oxfordshire          NA 1
18838 3,013 < 15,069 ft2 (280 < 1,400 m2)    Oxfordshire          NA 2
18839 < 3,013 ft2 (280m2)                    Oxfordshire        2023 1
18840 3,013 < 15,069 ft2 (280 < 1,400 m2)    Oxfordshire          NA 2

In [ ]:
# head() returns a set number of the first records.
head(store, n = 5)

  id         retailer               fascia
1 1010008812 The Co-operative Group The Co-operative Food
2 1010021060 Spar                   Spar
3 1010007877 The Co-operative Group The Co-operative Food
4 1010016823 Spar                   Spar
5 1010010459 Tesco                  Tesco
  store_name                                add_one
1 Co-op Holyhead Road - Chirk               Holyhead Road
2 Spar Glyn Ceiriog                         Cross Stores High Street
3 Co-op Blaenau Ffestiniog                  High Street
4 Spar - Cynwyd Post Office & General Store Cynwyd Post Office & General Store
5 Tesco Wrexham Superstore                  Plas Kynaston Lane
  add_two            town               suburb             postcode long_wgs
1 Chirk              Chirk                                 LL14 5NA -3.058428
2                    Glyn Ceiriog                          LL20 7EH -3.188270
3 Blaenau Ffestiniog Blaenau Ffestiniog Blaenau Ffestiniog LL41 3AG -3.934357
4 Station Road       Cynwyd                                LL21 0LA -3.405960
5 Off Well Street    Cefn-Mawr                             LL14 3AT -3.070395
  lat_wgs  bng_e    bng_n    pqi     open_date
1 52.94037 328966.9 338632.9 Rooftop       NA
2 52.93246 320226.8 337889.8 Rooftop 20230499
3 52.99474 270269.0 345908.0 Rooftop       NA
4 52.95915 305653.5 341122.8 Rooftop       NA
5 52.97315 328217.1 342292.0 Rooftop       NA
  size_band                              county  year size_level
1 < 3,013 ft2 (280m2)                    Clywd     NA 1
2 < 3,013 ft2 (280m2)                    Clywd   2023 1
3 3,013 < 15,069 ft2 (280 < 1,400 m2)    Gwynedd   NA 2
4 < 3,013 ft2 (280m2)                    Clywd     NA 1
5 15,069 < 30,138 ft2 (1,400 < 2,800 m2) Clywd     NA 3

In [ ]:
# tail() returns a set number of the last records.
tail(store, n = 5)

      id         retailer               fascia
18836 1010007793 The Co-operative Group The Co-operative Food
18837 1010021975 Cook                   Cook
18838 1010007999 The Co-operative Group The Co-operative Food
18839 1010021061 Spar                   Spar
18840 1010014305 Iceland                Iceland
      store_name            add_one               add_two
18836 Co-op Sonning Common  44 Wood Lane          Sonning Common
18837 Cook Henley-on-Thames 1 Oxford House
18838 Co-op Didcot          202 Broadway
18839 Spar Wantage          18 Wallingford Street
18840 Iceland Didcot        3-5 Market Place
      town             suburb       postcode long_wgs   lat_wgs  bng_e
18836 Sonning Common                RG4 9SL  -0.9815925 51.51740 470761.4
18837 Henley-on-Thames              RG9 1UR  -0.9036755 51.53636 476136.2
18838 Didcot           South Didcot OX11 8RN -1.2440674 51.60659 452446.7
18839 Wantage          Wantage      OX12 8AX -1.4245000 51.58831 439967.5
18840 Didcot           South Didcot OX11 7LE -1.2415885 51.60649 452618.5
      bng_n    pqi     open_date size_band
18836 180322.2 Rooftop       NA  < 3,013 ft2 (280m2)
18837 182508.9 Rooftop       NA  < 3,013 ft2 (280m2)
18838 190021.2 Rooftop       NA  3,013 < 15,069 ft2 (280 < 1,400 m2)
18839 187874.2 Rooftop 20230499  < 3,013 ft2 (280m2)
18840 190011.8 Rooftop       NA  3,013 < 15,069 ft2 (280 < 1,400 m2)
      county      year size_level
18836 Oxfordshire   NA 1
18837 Oxfordshire   NA 1
18838 Oxfordshire   NA 2
18839 Oxfordshire 2023 1
18840 Oxfordshire   NA 2

In [ ]:
# Values in columns are accessed with the '$' character.

store$retailer

    [1] "The Co-operative Group"
    [2] "Spar"
    [3] "The Co-operative Group"
    [4] "Spar"
    [5] "Tesco"
    [6] "Lidl"
    [7] "Tesco"
    [8] "Morrisons"
    [9] "Spar"
   [10] "Spar"
   [11] "Spar"
   [12] "Spar"
   [13] "Spar"
   [14] "Aldi"
   [15] "Aldi"
   [16] "Spar"
   [17] "Spar"
   [18] "Spar"
   [19] "Morrisons"
   [20] "Aldi"
   [21] "Spar"
   [22] "Spar"
   [23] "Spar"
   [24] "The Co-operative Group"
   [25] "Budgens"
   [26] "Lidl"
   [27] "Tesco"
   [28] "The Co-operative Group"
   [29] "Sainsburys"
   [30] "Tesco"
   [31] "Marks and Spencer"
   [32] "Marks and Spencer"
   [33] "Aldi"
   [34] "Morrisons"
   [35] "Tesco"
   [36] "Morrisons"
   [37] "Farmfoods"
   [38] "Tesco"
   [39] "Morrisons"
   [40] "Iceland"
   [41] "Spar"
   [42] "Spar"
   [43] "Sainsburys"
   [44] "Tesco"
   [45] "Tesco"
   [46] "Tesco"
   [47] "Farmfoods"
   [48] "The Co-operative Group"
   [49] "The Co-operative Group"
   [50] "Tesco"
   [51] "The Co-operative Group"
   [52] "Spar"
   [53] "The Co-operative Group"
   [54] "Morrisons"
   [55] "Tesco"
   [56] "Iceland"
   [57] "The Co-operative Group"
   [58] "Spar"
   [59] "Tesco"
   [60] "Tesco"
   [61] "Aldi"
   [62] "Tesco"
   [63] "Spar"
   [64] "Aldi"
   [65] "The Co-operative Group"
   [66] "Tesco"
   [67] "Lidl"
   [68] "The Co-operative Group"
   [69] "Morrisons"
   [70] "Waitrose"
   [71] "Asda"
   [72] "Asda"
   [73] "Tesco"
   [74] "Spar"
   [75] "Heron"
   [76] "Sainsburys"
   [77] "Aldi"
   [78] "Spar"
   [79] "Marks and Spencer"
   [80] "Iceland"
   [81] "Spar"
   [82] "Morrisons"
   [83] "Sainsburys"
   [84] "Sainsburys"
   [85] "Aldi"
   [86] "Morrisons"
   [87] "Asda"
   [88] "Spar"
   [89] "Asda"
   [90] "Spar"
   [91] "Morrisons"
   [92] "The Co-operative Group"
   [93] "Iceland"
   [94] "Aldi"
   [95] "Marks and Spencer"
   [96] "Tesco"
   [97] "Spar"
   [98] "Morrisons"
   [99] "Tesco"
  [100] "Spar"
  [101] "Aldi"
  [102] "The Co-operative Group"
  [103] "Farmfoods"
  [104] "Iceland"
  [105] "Asda"
  [106] "Spar"
  [107] "Tesco"
  [108] "Spar"
  [109] "Tesco"
  [110] "Iceland"
  [111] "Marks and Spencer"
  [112] "Asda"
  [113] "Tesco"
  [114] "Tesco"
  [115] "Tesco"
  [116] "Farmfoods"
  [117] "Farmfoods"
  [118] "Lidl"
  [119] "Tesco"
  [120] "Asda"
  [121] "Farmfoods"
  [122] "Aldi"
  [123] "Lidl"
  [124] "Iceland"
  [125] "Heron"
  [126] "The Co-operative Group"
  [127] "Asda"
  [128] "Morrisons"
  [129] "Sainsburys"
  [130] "Asda"
  [131] "Morrisons"
  [132] "The Co-operative Group"
  [133] "Iceland"
  [134] "Spar"
  [135] "Iceland"
  [136] "Lidl"
  [137] "Tesco"
  [138] "Tesco"
  [139] "Spar"
  [140] "Spar"
  [141] "Marks and Spencer"
  [142] "Asda"
  [143] "Lidl"
  [144] "Tesco"
  [145] "Farmfoods"
  [146] "Spar"
  [147] "Spar"
  [148] "Iceland"
  [149] "The Co-operative Group"
  [150] "The Co-operative Group"
  [151] "The Co-operative Group"
  [152] "Spar"
  [153] "Spar"
  [154] "Morrisons"
  [155] "Iceland"
  [156] "Sainsburys"
  [157] "Morrisons"
  [158] "Morrisons"
  [159] "Farmfoods"
  [160] "Spar"
  [161] "Iceland"
  [162] "Farmfoods"
  [163] "Aldi"
  [164] "Lidl"
  [165] "Spar"
  [166] "Asda"
  [167] "The Co-operative Group"
  [168] "Lidl"
  [169] "The Co-operative Group"
  [170] "Tesco"
  [171] "Tesco"
  [172] "Morrisons"
  [173] "Iceland"
  [174] "The Co-operative Group"
  [175] "The Co-operative Group"
  [176] "The Co-operative Group"
  [177] "Spar"
  [178] "Spar"
  [179] "Sainsburys"
  [180] "Marks and Spencer"
  [181] "Spar"
  [182] "Lidl"
  [183] "Iceland"
  [184] "Iceland"
  [185] "The Co-operative Group"
  [186] "Tesco"
  [187] "Morrisons"
  [188] "The Co-operative Group"
  [189] "Aldi"
  [190] "The Co-operative Group"
  [191] "Lidl"
  [192] "Marks and Spencer"
  [193] "Tesco"
  [194] "The Co-operative Group"
  [195] "Spar"
  [196] "Spar"
  [197] "Morrisons"
  [198] "Asda"
  [199] "Farmfoods"
  [200] "Asda"
  [201] "Asda"
  [202] "Sainsburys"
  [203] "Aldi"
  [204] "Morrisons"
  [205] "Lidl"
  [206] "Spar"
  [207] "Iceland"
  [208] "Spar"
  [209] "Morrisons"
  [210] "Aldi"
  [211] "Tesco"
  [212] "Farmfoods"
  [213] "Morrisons"
  [214] "Tesco"
  [215] "Iceland"
  [216] "Aldi"
  [217] "Asda"
  [218] "The Co-operative Group"
  [219] "Spar"
  [220] "Lidl"
  [221] "Morrisons"
  [222] "Morrisons"
  [223] "The Co-operative Group"
  [224] "Spar"
  [225] "Asda"
  [226] "Asda"
  [227] "Spar"
  [228] "The Co-operative Group"
  [229] "Aldi"
  [230] "Asda"
  [231] "Morrisons"
  [232] "The Co-operative Group"
  [233] "The Co-operative Group"
  [234] "Spar"
  [235] "The Co-operative Group"
  [236] "The Co-operative Group"
  [237] "Morrisons"
  [238] "Iceland"
  [239] "Spar"
  [240] "Spar"
  [241] "Spar"
  [242] "Lidl"
  [243] "Sainsburys"
  [244] "Morrisons"
  [245] "Marks and Spencer"
  [246] "Spar"
  [247] "Tesco"
  [248] "The Co-operative Group"
  [249] "Iceland"
  [250] "Morrisons"
  [251] "The Co-operative Group"
  [252] "Spar"
  [253] "Aldi"
  [254] "Asda"
  [255] "Farmfoods"
  [256] "Morrisons"
  [257] "Asda"
  [258] "Lidl"
  [259] "Tesco"
  [260] "Tesco"
  [261] "The Co-operative Group"
  [262] "Lidl"
  [263] "Asda"
  [264] "Asda"
  [265] "Tesco"
  [266] "Sainsburys"
  [267] "The Co-operative Group"
  [268] "The Co-operative Group"
  [269] "Tesco"
  [270] "The Co-operative Group"
  [271] "Tesco"
  [272] "Iceland"
  [273] "Farmfoods"
  [274] "Asda"
  [275] "Sainsburys"
  [276] "Aldi"
  [277] "Lidl"
  [278] "Tesco"
  [279] "Spar"
  [280] "Marks and Spencer"
  [281] "Aldi"
  [282] "Asda"
  [283] "Marks and Spencer"
  [284] "The Co-operative Group"
  [285] "Lidl"
  [286] "Spar"
  [287] "The Co-operative Group"
  [288] "Asda"
  [289] "The Co-operative Group"
  [290] "Tesco"
  [291] "The Co-operative Group"
  [292] "The Co-operative Group"
  [293] "Morrisons"
  [294] "Spar"
  [295] "Asda"
  [296] "Aldi"
  [297] "Aldi"
  [298] "Asda"
  [299] "Asda"
  [300] "Aldi"
  [301] "Spar"
  [302] "The Co-operative Group"
  [303] "Lidl"
  [304] "The Co-operative Group"
  [305] "Iceland"
  [306] "The Co-operative Group"
  [307] "Spar"
  [308] "Asda"
  [309] "Morrisons"
  [310] "Spar"
  [311] "Tesco"
  [312] "Spar"
  [313] "Morrisons"
  [314] "The Co-operative Group"
  [315] "Spar"
  [316] "Tesco"
  [317] "Aldi"
  [318] "Sainsburys"
  [319] "Tesco"
  [320] "Tesco"
  [321] "The Co-operative Group"
  [322] "Aldi"
  [323] "Asda"
  [324] "Asda"
  [325] "Spar"
  [326] "The Co-operative Group"
  [327] "Tesco"
  [328] "Waitrose"
  [329] "Morrisons"
  [330] "Spar"
  [331] "Asda"
  [332] "Asda"
  [333] "Aldi"
  [334] "Lidl"
  [335] "The Co-operative Group"
  [336] "Marks and Spencer"
  [337] "Waitrose"
  [338] "Asda"
  [339] "Morrisons"
  [340] "Spar"
  [341] "Tesco"
  [342] "Spar"
  [343] "Morrisons"
  [344] "Morrisons"
  [345] "Spar"
  [346] "Aldi"
  [347] "Lidl"
  [348] "Spar"
  [349] "Tesco"
  [350] "Morrisons"
  [351] "Tesco"
  [352] "Spar"
  [353] "The Co-operative Group"
  [354] "Morrisons"
  [355] "Asda"
  [356] "Spar"
  [357] "Iceland"
  [358] "Spar"
  [359] "Spar"
  [360] "Iceland"
  [361] "Tesco"
  [362] "Spar"
  [363] "Spar"
  [364] "The Co-operative Group"
  [365] "Asda"
  [366] "Spar"
  [367] "Spar"
  [368] "Spar"
  [369] "Tesco"
  [370] "Marks and Spencer"
  [371] "Farmfoods"
  [372] "The Co-operative Group"
  [373] "Asda"
  [374] "The Co-operative Group"
  [375] "The Co-operative Group"
  [376] "Morrisons"
  [377] "The Co-operative Group"
  [378] "Lidl"
  [379] "Iceland"
  [380] "Lidl"
  [381] "The Co-operative Group"
  [382] "Spar"
  [383] "Aldi"
  [384] "Marks and Spencer"
  [385] "Spar"
  [386] "Morrisons"
  [387] "The Co-operative Group"
  [388] "Farmfoods"
  [389] "Asda"
  [390] "The Co-operative Group"
  [391] "Spar"
  [392] "Spar"
  [393] "Spar"
  [394] "Spar"
  [395] "Morrisons"
  [396] "Tesco"
  [397] "Morrisons"
  [398] "The Co-operative Group"
  [399] "Morrisons"
  [400] "Asda"
  [401] "Marks and Spencer"
  [402] "Spar"
  [403] "Iceland"
  [404] "Asda"
  [405] "Asda"
  [406] "Morrisons"
  [407] "Morrisons"
  [408] "Makro"
  [409] "Asda"
  [410] "Iceland"
  [411] "Tesco"
  [412] "Lidl"
  [413] "Tesco"
  [414] "The Co-operative Group"
  [415] "Spar"
  [416] "The Co-operative Group"
  [417] "The Co-operative Group"
  [418] "Iceland"
  [419] "Asda"
  [420] "Iceland"
  [421] "Lidl"
  [422] "Tesco"
  [423] "Asda"
  [424] "Tesco"
  [425] "Morrisons"
  [426] "The Co-operative Group"
  [427] "Costco"
  [428] "Sainsburys"
  [429] "Tesco"
  [430] "Lidl"
  [431] "Tesco"
  [432] "Tesco"
  [433] "Waitrose"
  [434] "The Co-operative Group"
  [435] "The Co-operative Group"
  [436] "Marks and Spencer"
  [437] "Tesco"
  [438] "The Co-operative Group"
  [439] "The Co-operative Group"
  [440] "Spar"
  [441] "Spar"
  [442] "Marks and Spencer"
  [443] "Morrisons"
  [444] "Aldi"
  [445] "Aldi"
  [446] "Sainsburys"
  [447] "The Co-operative Group"
  [448] "Tesco"
  [449] "The Co-operative Group"
  [450] "Farmfoods"
  [451] "Tesco"
  [452] "Sainsburys"
  [453] "Tesco"
  [454] "Morrisons"
  [455] "Spar"
  [456] "Spar"
  [457] "Morrisons"
  [458] "Asda"
  [459] "Lidl"
  [460] "Lidl"
  [461] "Spar"
  [462] "Sainsburys"
  [463] "Tesco"
  [464] "Spar"
  [465] "Morrisons"
  [466] "Tesco"
  [467] "The Co-operative Group"
  [468] "Iceland"
  [469] "Lidl"
  [470] "Iceland"
  [471] "Lidl"
  [472] "Lidl"
  [473] "Waitrose"
  [474] "Spar"
  [475] "Sainsburys"
  [476] "Tesco"
  [477] "The Co-operative Group"
  [478] "The Co-operative Group"
  [479] "The Co-operative Group"
  [480] "Tesco"
  [481] "Spar"
  [482] "Aldi"
  [483] "Tesco"
  [484] "Cook"
  [485] "The Co-operative Group"
  [486] "Tesco"
  [487] "Spar"
  [488] "Tesco"
  [489] "Sainsburys"
  [490] "Morrisons"
  [491] "Tesco"
  [492] "Aldi"
  [493] "Spar"
  [494] "Iceland"
  [495] "Asda"
  [496] "Iceland"
  [497] "Heron"
  [498] "Tesco"
  [499] "Spar"
  [500] "Spar"
  [501] "Morrisons"
  [502] "Spar"
  [503] "Lidl"
  [504] "Tesco"
  [505] "Farmfoods"
  [506] "Tesco"
  [507] "Morrisons"
  [508] "Farmfoods"
  [509] "Morrisons"
  [510] "Spar"
  [511] "Lidl"
  [512] "Marks and Spencer"
  [513] "Budgens"
  [514] "Tesco"
  [515] "Waitrose"
  [516] "Morrisons"
  [517] "Morrisons"
  [518] "Morrisons"
  [519] "Asda"
  [520] "Asda"
  [521] "Morrisons"
  [522] "Iceland"
  [523] "Asda"
  [524] "Aldi"
  [525] "Tesco"
  [526] "Lidl"
  [527] "Asda"
  [528] "Spar"
  [529] "Lidl"
  [530] "Tesco"
  [531] "Asda"
  [532] "The Co-operative Group"
  [533] "Asda"
  [534] "Tesco"
  [535] "Spar"
  [536] "Sainsburys"
  [537] "The Co-operative Group"
  [538] "Asda"
  [539] "Morrisons"
  [540] "Farmfoods"
  [541] "Marks and Spencer"
  [542] "Heron"
  [543] "The Co-operative Group"
  [544] "The Southern Co-operative"
  [545] "Morrisons"
  [546] "Asda"
  [547] "Tesco"
  [548] "Morrisons"
  [549] "Sainsburys"
  [550] "The Co-operative Group"
  [551] "Cook"
  [552] "Marks and Spencer"
  [553] "Aldi"
  [554] "Morrisons"
  [555] "Morrisons"
  [556] "Tesco"
  [557] "Tesco"
  [558] "Morrisons"
  [559] "Lidl"
  [560] "Morrisons"
  [561] "Asda"
  [562] "Spar"
  [563] "Tesco"
  [564] "Marks and Spencer"
  [565] "The Co-operative Group"
  [566] "The Co-operative Group"
  [567] "Aldi"
  [568] "Spar"
  [569] "Spar"
  [570] "Morrisons"
  [571] "Marks and Spencer"
  [572] "Sainsburys"
  [573] "Tesco"
  [574] "Tesco"
  [575] "The Co-operative Group"
  [576] "Heron"
  [577] "Morrisons"
  [578] "Aldi"
  [579] "Aldi"
  [580] "Lidl"
  [581] "Booths"
  [582] "Tesco"
  [583] "Marks and Spencer"
  [584] "Morrisons"
  [585] "Heron"
  [586] "Tesco"
  [587] "Morrisons"
  [588] "Tesco"
  [589] "The Co-operative Group"
  [590] "Morrisons"
  [591] "Tesco"
  [592] "Tesco"
  [593] "Asda"
  [594] "Lidl"
  [595] "Iceland"
  [596] "Tesco"
  [597] "Sainsburys"
  [598] "The Co-operative Group"
  [599] "The Co-operative Group"
  [600] "Morrisons"
  [601] "Morrisons"
  [602] "The Co-operative Group"
  [603] "Spar"
  [604] "Iceland"
  [605] "Booths"
  [606] "Marks and Spencer"
  [607] "Sainsburys"
  [608] "Tesco"
  [609] "Morrisons"
  [610] "Morrisons"
  [611] "Booths"
  [612] "The Co-operative Group"
  [613] "Morrisons"
  [614] "Tesco"
  [615] "The Co-operative Group"
  [616] "Aldi"
  [617] "Spar"
  [618] "Spar"
  [619] "Tesco"
  [620] "The Co-operative Group"
  [621] "Tesco"
  [622] "The Co-operative Group"
  [623] "Spar"
  [624] "The Co-operative Group"
  [625] "Morrisons"
  [626] "Asda"
  [627] "Asda"
  [628] "Iceland"
  [629] "Aldi"
  [630] "Morrisons"
  [631] "Spar"
  [632] "Tesco"
  [633] "Morrisons"
  [634] "Asda"
  [635] "Sainsburys"
  [636] "Tesco"
  [637] "The Co-operative Group"
  [638] "Cook"
  [639] "The Co-operative Group"
  [640] "The Co-operative Group"
  [641] "Asda"
  [642] "Tesco"
  [643] "Tesco"
  [644] "Tesco"
  [645] "Marks and Spencer"
  [646] "Lidl"
  [647] "Marks and Spencer"
  [648] "Budgens"
  [649] "Tesco"
  [650] "Spar"
  [651] "The Co-operative Group"
  [652] "Asda"
  [653] "Tesco"
  [654] "Tesco"
  [655] "Farmfoods"
  [656] "Lidl"
  [657] "Morrisons"
  [658] "The Co-operative Group"
  [659] "Tesco"
  [660] "Tesco"
  [661] "Tesco"
  [662] "The Co-operative Group"
  [663] "Asda"
  [664] "The Co-operative Group"
  [665] "Sainsburys"
  [666] "Spar"
  [667] "The Co-operative Group"
  [668] "Aldi"
  [669] "Lidl"
  [670] "Tesco"
  [671] "Tesco"
  [672] "Asda"
  [673] "The Co-operative Group"
  [674] "Morrisons"
  [675] "The Co-operative Group"
  [676] "Sainsburys"
  [677] "Tesco"
  [678] "Spar"
  [679] "The Co-operative Group"
  [680] "The Co-operative Group"
  [681] "Tesco"
  [682] "Sainsburys"
  [683] "Sainsburys"
  [684] "Tesco"
  [685] "The Co-operative Group"
  [686] "Aldi"
  [687] "The Co-operative Group"
  [688] "Marks and Spencer"
  [689] "Tesco"
  [690] "Tesco"
  [691] "Aldi"
  [692] "Booths"
  [693] "Morrisons"
  [694] "The Co-operative Group"
  [695] "Makro"
  [696] "Heron"
  [697] "Lidl"
  [698] "Tesco"
  [699] "Lidl"
  [700] "Iceland"
  [701] "Tesco"
  [702] "Spar"
  [703] "Spar"
  [704] "Asda"
  [705] "Farmfoods"
  [706] "Tesco"
  [707] "Tesco"
  [708] "Tesco"
  [709] "Marks and Spencer"
  [710] "Tesco"
  [711] "The Co-operative Group"
  [712] "Heron"
  [713] "Morrisons"
  [714] "Aldi"
  [715] "Tesco"
  [716] "Spar"
  [717] "The Co-operative Group"
  [718] "Tesco"
  [719] "Lidl"
  [720] "Heron"
  [721] "Sainsburys"
  [722] "Farmfoods"
  [723] "Iceland"
  [724] "Lidl"
  [725] "Tesco"
  [726] "Iceland"
  [727] "Heron"
  [728] "Iceland"
  [729] "Asda"
  [730] "Spar"
  [731] "Asda"
  [732] "Iceland"
  [733] "Tesco"
  [734] "Heron"
  [735] "Farmfoods"
  [736] "Tesco"
  [737] "Heron"
  [738] "Lidl"
  [739] "Tesco"
  [740] "Asda"
  [741] "Tesco"
  [742] "Lidl"
  [743] "The Co-operative Group"
  [744] "Aldi"
  [745] "Sainsburys"
  [746] "Iceland"
  [747] "Iceland"
  [748] "Asda"
  [749] "Heron"
  [750] "The Co-operative Group"
  [751] "Morrisons"
  [752] "The Co-operative Group"
  [753] "Central England Co-operative"
  [754] "Marks and Spencer"
  [755] "Iceland"
  [756] "The Co-operative Group"
  [757] "Asda"
  [758] "Lidl"
  [759] "Morrisons"
  [760] "Morrisons"
  [761] "Aldi"
  [762] "Marks and Spencer"
  [763] "Iceland"
  [764] "Marks and Spencer"
  [765] "Morrisons"
  [766] "Morrisons"
  [767] "Spar"
  [768] "Heron"
  [769] "Iceland"
  [770] "Asda"
  [771] "Heron"
  [772] "Morrisons"
  [773] "Asda"
  [774] "Spar"
  [775] "Lidl"
  [776] "The Co-operative Group"
  [777] "Lidl"
  [778] "Iceland"
  [779] "Spar"
  [780] "Asda"
  [781] "Asda"
  [782] "Asda"
  [783] "Morrisons"
  [784] "The Co-operative Group"
  [785] "Morrisons"
  [786] "Aldi"
  [787] "The Co-operative Group"
  [788] "Iceland"
  [789] "Morrisons"
  [790] "Aldi"
  [791] "Aldi"
  [792] "Tesco"
  [793] "Heron"
  [794] "Marks and Spencer"
  [795] "Aldi"
  [796] "The Co-operative Group"
  [797] "Spar"
  [798] "Farmfoods"
  [799] "Morrisons"
  [800] "Morrisons"
  [801] "The Co-operative Group"
  [802] "Aldi"
  [803] "Morrisons"
  [804] "Tesco"
  [805] "Lidl"
  [806] "Spar"
  [807] "Asda"
  [808] "Sainsburys"
  [809] "Scottish Midland Co-operative"
  [810] "Morrisons"
  [811] "Booths"
  [812] "Marks and Spencer"
  [813] "Spar"
  [814] "Asda"
  [815] "Tesco"
  [816] "Aldi"
  [817] "Booths"
  [818] "The Co-operative Group"
  [819] "Tesco"
  [820] "The Co-operative Group"
  [821] "Asda"
  [822] "Iceland"
  [823] "The Co-operative Group"
  [824] "The Co-operative Group"
  [825] "Iceland"
  [826] "The Co-operative Group"
  [827] "Spar"
  [828] "Aldi"
  [829] "Booths"
  [830] "Sainsburys"
  [831] "Morrisons"
  [832] "Booths"
  [833] "The Co-operative Group"
  [834] "Marks and Spencer"
  [835] "Spar"
  [836] "Spar"
  [837] "Booths"
  [838] "Tesco"
  [839] "Spar"
  [840] "Spar"
  [841] "Tesco"
  [842] "Morrisons"
  [843] "Asda"
  [844] "Spar"
  [845] "The Co-operative Group"
  [846] "Spar"
  [847] "Tesco"
  [848] "Iceland"
  [849] "Langdale Co-operative Society"
  [850] "The Co-operative Group"
  [851] "Spar"
  [852] "Tesco"
  [853] "Booths"
  [854] "Tesco"
  [855] "The Co-operative Group"
  [856] "The Co-operative Group"
  [857] "The Co-operative Group"
  [858] "Aldi"
  [859] "Farmfoods"
  [860] "Morrisons"
  [861] "Tesco"
  [862] "Heron"
  [863] "Morrisons"
  [864] "Asda"
  [865] "Marks and Spencer"
  [866] "Sainsburys"
  [867] "Marks and Spencer"
  [868] "Asda"
  [869] "Tesco"
  [870] "Tesco"
  [871] "Iceland"
  [872] "Asda"
  [873] "Aldi"
  [874] "Aldi"
  [875] "Farmfoods"
  [876] "Morrisons"
  [877] "The Co-operative Group"
  [878] "Iceland"
  [879] "Tesco"
  [880] "The Co-operative Group"
  [881] "Morrisons"
  [882] "Tesco"
  [883] "Sainsburys"
  [884] "Tesco"
  [885] "Iceland"
  [886] "Tesco"
  [887] "Asda"
  [888] "Sainsburys"
  [889] "Iceland"
  [890] "Lidl"
  [891] "Farmfoods"
  [892] "Asda"
  [893] "Asda"
  [894] "Tesco"
  [895] "Tesco"
  [896] "Farmfoods"
  [897] "Farmfoods"
  [898] "Morrisons"
  [899] "Iceland"
  [900] "Spar"
  [901] "Booths"
  [902] "Sainsburys"
  [903] "Lidl"
  [904] "Marks and Spencer"
  [905] "Lidl"
  [906] "The Co-operative Group"
  [907] "Tesco"
  [908] "Tesco"
  [909] "Tesco"
  [910] "Aldi"
  [911] "Asda"
  [912] "The Co-operative Group"
  [913] "The Co-operative Group"
  [914] "Marks and Spencer"
  [915] "Aldi"
  [916] "Spar"
  [917] "Spar"
  [918] "Spar"
  [919] "Aldi"
  [920] "The Co-operative Group"
  [921] "Tesco"
  [922] "Spar"
  [923] "Asda"
  [924] "Spar"
  [925] "Spar"
  [926] "Spar"
  [927] "Spar"
  [928] "The Co-operative Group"
  [929] "Tesco"
  [930] "The Co-operative Group"
  [931] "Aldi"
  [932] "Spar"
  [933] "Iceland"
  [934] "Asda"
  [935] "The Co-operative Group"
  [936] "Lidl"
  [937] "Lidl"
  [938] "Tesco"
  [939] "Iceland"
  [940] "Marks and Spencer"
  [941] "Lidl"
  [942] "Sainsburys"
  [943] "Marks and Spencer"
  [944] "Spar"
  [945] "Spar"
  [946] "Spar"
  [947] "Aldi"
  [948] "Iceland"
  [949] "Heron"
  [950] "Asda"
  [951] "Tesco"
  [952] "Farmfoods"
  [953] "The Co-operative Group"
  [954] "Heron"
  [955] "Sainsburys"
  [956] "Morrisons"
  [957] "The Co-operative Group"
  [958] "Marks and Spencer"
  [959] "Lidl"
  [960] "The Co-operative Group"
  [961] "The Co-operative Group"
  [962] "Sainsburys"
  [963] "Asda"
  [964] "Iceland"
  [965] "Aldi"
  [966] "Iceland"
  [967] "Morrisons"
  [968] "Iceland"
  [969] "Morrisons"
  [970] "The Co-operative Group"
  [971] "Tesco"
  [972] "Lidl"
  [973] "The Co-operative Group"
  [974] "The Co-operative Group"
  [975] "Spar"
  [976] "Spar"
  [977] "Spar"
  [978] "The Co-operative Group"
  [979] "Tesco"
  [980] "Aldi"
  [981] "The Co-operative Group"
  [982] "Cook"
  [983] "Lidl"
  [984] "Aldi"
  [985] "Sainsburys"
  [986] "Aldi"
  [987] "The Co-operative Group"
  [988] "Spar"
  [989] "The Co-operative Group"
  [990] "Morrisons"
  [991] "Aldi"
  [992] "Morrisons"
  [993] "Iceland"
  [994] "Morrisons"
  [995] "Asda"
  [996] "The Co-operative Group"
  [997] "The Co-operative Group"
  [998] "Asda"
  [999] "Morrisons"
 [1000] "Tesco"
 [1001] "Spar"
 [1002] "Tesco"
 [1003] "Marks and Spencer"
 [1004] "The Co-operative Group"
 [1005] "Morrisons"
 [1006] "Morrisons"
 [1007] "Asda"
 [1008] "Aldi"
 [1009] "The Co-operative Group"
 [1010] "Aldi"
 [1011] "Spar"
 [1012] "Tesco"
 [1013] "Morrisons"

These functions are all 'base' R commands. Libraries provide different functioality that build on each other to perform higher-level operations with minmial consistent syntax.

# Introducing *dpylr*

*dpylr* defines a powerful syntax that provides a simpler more consistent way of working with tabular data that always returns a table, specifically a type of table called a '[tibble](https://tibble.tidyverse.org/reference/tibble.html)', which is an 'extended' data table. The details do not matter.

For example,

In [ ]:
# dpylr (count) returns the number of rows
count(store)

  n
1 18840

This command may, however also be written as,
```
store %>%
  count()
```
'%>%' passes the result of one statement to another allowing them to be srung together to undertake complex queries and manipulations. Here the content of 'store' is passed to count.

In [ ]:
store %>%
  count()

  n
1 18840

Emissions data is available for eleven retailers, so one of the first questions to ask is which retailers are in the Retail Points and how many stores each has?

In [ ]:
# dpylr distinct() returns unique values.

store %>% distinct(retailer)

   retailer
1  The Co-operative Group
2  Spar
3  Tesco
4  Lidl
5  Morrisons
6  Aldi
7  Budgens
8  Sainsburys
9  Marks and Spencer
10 Farmfoods
11 Iceland
12 Waitrose
13 Asda
14 Heron
15 Makro
16 Costco
17 Cook
18 The Southern Co-operative
19 Booths
20 Central England Co-operative
21 Scottish Midland Co-operative
22 Langdale Co-operative Society
23 Clydebank Co-operative
24 The Radstock Co-operative Society
25 Midcounties Co-operative
26 Channel Islands Co-operative Society
27 Amazon
28 Heart of England Co-operative
29 Tamworth Co-operative Society
30 Lincolnshire Co-operative
31 Dunnes Stores
32 East of England Co-operative
33 Chelmsford Star Co-operative Society
34 Whole Foods Market
35 Planet Organic
36 Coniston Co-operative Society
37 Allendale Co-operative Society

In [ ]:
# To count the number of unique retailers chain store, distinct(), and count()
store %>%
  distinct(retailer) %>%
  count()

  n
1 37

Counting the number of stores each retailer has and their percentage is an example of a more complex dpylr query that was 'vibe' coded by asking Gemeni to,

> *"Count the number of store rows for each retailer and calculate the percent of records for each"*

Helpfully, Gemeni added a sort statement despite not being requested.

In [ ]:
# To count the number of stores each retailer has and calculate their percentage
store %>%
  group_by(retailer) %>%
  summarise(count = n(), .groups = "drop") %>%
  mutate(percent = count / sum(count) * 100) %>%
  arrange(desc(percent))

   retailer                             count percent
1  Tesco                                2909  15.440552017
2  The Co-operative Group               2467  13.094479830
3  Spar                                 2118  11.242038217
4  Morrisons                            1745   9.262208068
5  Sainsburys                           1444   7.664543524
6  Asda                                 1106   5.870488323
7  Marks and Spencer                    1056   5.605095541
8  Aldi                                 1043   5.536093418
9  Lidl                                 1010   5.360934183
10 Iceland                               972   5.159235669
11 Waitrose                              424   2.250530786
12 Budgens                               385   2.043524416
13 Farmfoods                             351   1.863057325
14 Heron                                 313   1.661358811
15 The Southern Co-operative             257   1.364118896
16 Central England Co-operative          236   1.252653928
17 Midcounties Co-operative              218   1.157112527
18 Scottish Midland Co-operative         185   0.981953291
19 East of England Co-operative          132   0.700636943
20 Cook                                  105   0.557324841
21 Lincolnshire Co-operative              96   0.509554140
22 Chelmsford Star Co-operative Society   39   0.207006369
23 Heart of England Co-operative          32   0.169851380
24 Costco                                 29   0.153927813
25 Booths                                 26   0.138004246
26 Channel Islands Co-operative Society   26   0.138004246
27 Makro                                  26   0.138004246
28 Amazon                                 21   0.111464968
29 The Radstock Co-operative Society      20   0.106157113
30 Dunnes Stores                          15   0.079617834
31 Tamworth Co-operative Society          11   0.058386412
32 Planet Organic                          9   0.047770701
33 Clydebank Co-operative                  6   0.031847134
34 Whole Foods Market                      5   0.026539278
35 Allendale Co-operative Society          1   0.005307856
36 Coniston Co-operative Society           1   0.005307856
37 Langdale Co-operative Society           1   0.005307856

# Clean Store Area

In the Geolytix dataset, stores are assigned to one of five size classes encoded as both *size_level* and *size_band* fields.

In [ ]:
# Unique size levels
store %>%
  distinct(size_level)

# Unique size bands
store %>%
  distinct(size_band)

  size_level
1  1
2  2
3  3
4  4
5  5
6 NA

  size_band
1 < 3,013 ft2 (280m2)
2 3,013 < 15,069 ft2 (280 < 1,400 m2)
3 15,069 < 30,138 ft2 (1,400 < 2,800 m2)
4 30,138 ft2 > (2,800 m2)
5 Over 30,138
6 NA

The base table() fuction is a useful way of getting the number of records for each combination of class pairs.

In [ ]:
# base table() function counts records by one or more variable
table(store$size_band, store$size_level, useNA = "always")

                                             1     2     3     4     5  <NA>
  < 3,013 ft2 (280m2)                    11416     0     0     0     0     0
  15,069 < 30,138 ft2 (1,400 < 2,800 m2)     0     0  1103     0     0     0
  3,013 < 15,069 ft2 (280 < 1,400 m2)        0  4889     0     0     0     0
  30,138 ft2 > (2,800 m2)                    0     0     0  1428     0     0
  Over 30,138                                0     0     0     0     3     0
  <NA>                                       0     0     0     0     0     1

The number of  size band and level records correspond, but one record is has NA values. Let's find out what it is.

In [ ]:
# is.na() finds NAs.
# select(), which limits which columns are returned
store %>%
filter(is.na(size_level)) %>%
    select(retailer, store_name, add_one, suburb, town, postcode, year, size_level, size_band)

  retailer               store_name                   add_one      suburb
1 The Co-operative Group Co-op Welling - Wrotham Road Wrotham Road Welling
  town   postcode year size_level size_band
1 London DA16 1LS 2024 NA         NA

The floor area of this store was measured from OS Mastermap data supplied through [Edina Digimap](https://digimap.edina.ac.uk/) at 820m<sup>2</sup>, within *size_level* = 2.

Use dpylr *mutate()* to update 'size_level' and 'size_band'.

In [ ]:
# WARNING
# This code updates the values of ALL records with NA values.
# This may not be approriate if there were more than one NA record.
store <- store %>%
  mutate(size_level = ifelse(is.na(size_level), 2, size_level)) %>%
  mutate(size_band = ifelse(is.na(size_band), "3,013 < 15,069 ft2 (280 < 1,400 m2)", size_band))

# Clean Year
The 'year' field stores the year the store opened.

Use *table()* to count the number of stores recorded as opening each year.

In [ ]:
table(store$year, useNA = "ifany")

    1  1855  1874  1898  1950  1967  1975  1978  1985  1989  1990  1992  1993
    1     1     1     2     1     1     1     2     1     1     1     1     2
 1995  1997  2000  2001  2002  2004  2007  2008  2009  2010  2011  2012  2013
    1     1     1     3     1     1     2     2     8     4    12     8     4
 2014  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024  <NA>
   20   362   362   736   334   502   461   428   670   934  1204 12763

There are four things to note:

1. One store is recorded as having opened in 1AD!
2. Far fewer stores are recorded as having opened between 1855 and 2014 than subsequent years.
3. Most stores do not have year recorded.
4. Store closure is not recorded.


A store opening in 1AD is unrealistic, so may be assumed an error and year changed to NA.

In [ ]:
# Update year = 1 to NA
store <- mutate(store, year = ifelse(year == 1, NA, year))

#Check
table(store$year, useNA = "ifany")

 1855  1874  1898  1950  1967  1975  1978  1985  1989  1990  1992  1993  1995
    1     1     2     1     1     1     2     1     1     1     1     2     1
 1997  2000  2001  2002  2004  2007  2008  2009  2010  2011  2012  2013  2014
    1     1     3     1     1     2     2     8     4    12     8     4    20
 2015  2016  2017  2018  2019  2020  2021  2022  2023  2024  <NA>
  362   362   736   334   502   461   428   670   934  1204 12764

The Retail points data set was first released in 2014. Given the difference in  stores recorded as opening, it is reasonable to assume that the opening year of all stores existing in 2014 may not have been known. If this is the case, then 2014 is the **baseline** year to which new stores are added in subsequent years.

In [ ]:
# Copy year to year_built

store$year_built <- store$year

# Update the year values equal or less than 2014 OR (pipe character '|') NA to 2014.
store <- store %>%
  mutate(year = ifelse(year <= 2014 | is.na(store$year), 2014, year))

# Check the output
table(store$retailer, store$year, useNA = "ifany")

                                       2014 2015 2016 2017 2018 2019 2020 2021
  Aldi                                  498   70   42   94   66   60   51   57
  Allendale Co-operative Society          1    0    0    0    0    0    0    0
  Amazon                                  0    0    0    0    0    0    0   11
  Asda                                  577   31    9    8    1    0    1    0
  Booths                                 22    4    0    0    0    0    0    0
  Budgens                                56    1   10   40    4   75   24    7
  Central England Co-operative          174    0    0   31    8    3    0    3
  Channel Islands Co-operative Society   20    0    1    2    1    0    0    0
  Chelmsford Star Co-operative Society   32    0    0    4    3    0    0    0
  Clydebank Co-operative                  5    0    0    1    0    0    0    0
  Coniston Co-operative Society           1    0    0    0    0    0    0    0
  Cook                                   97    0    0    0    0    0    0    0
  Costco                                 26    1    1    0    0    1    0    0
  Dunnes Stores                          15    0    0    0    0    0    0    0
  East of England Co-operative          110    0    1   10    3    0    0    0
  Farmfoods                             274    1    4    9    1    0    9   11
  Heart of England Co-operative          27    0    0    2    0    1    1    0
  Heron                                 243    0    0    4    4    6    5   14
  Iceland                               781    1    7   11   37   54   24   16
  Langdale Co-operative Society           1    0    0    0    0    0    0    0
  Lidl                                  556   24   29   51   55   61   59   65
  Lincolnshire Co-operative              72    1    1    6    0    0    0    0
  Makro                                  25    0    0    1    0    0    0    0
  Marks and Spencer                     651   32  125   75   41   31   17   23
  Midcounties Co-operative              158    0    0   17    5    4    1    7
  Morrisons                             469    7    1    0    3    3  124  121
  Planet Organic                          3    0    0    0    0    1    3    2
  Sainsburys                           1126  104   18   74    8   18   14   22
  Scottish Midland Co-operative         119    0    0   61    2    1    0    0
  Spar                                 1908    0    0    0    0    0    0    0
  Tamworth Co-operative Society          10    0    0    0    0    1    0    0
  Tesco                                2485   68   33   21    9    3   74   32
  The Co-operative Group               1770    2   68  150   71  171   50   36
  The Radstock Co-operative Society      12    1    0    2    3    0    1    0
  The Southern Co-operative             129    1    1   55    6    8    3    1
  Waitrose                              389   13   11    7    3    0    0    0
  Whole Foods Market                      5    0    0    0    0    0    0    0

                                       2022 2023 2024
  Aldi                                   44   33   28
  Allendale Co-operative Society          0    0    0
  Amazon                                  5    4    1
  Asda                                    2  214  263
  Booths                                  0    0    0
  Budgens                                65   26   77
  Central England Co-operative            8    6    3
  Channel Islands Co-operative Society    0    2    0
  Chelmsford Star Co-operative Society    0    0    0
  Clydebank Co-operative                  0    0    0
  Coniston Co-operative Society           0    0    0
  Cook                                    0    2    6
  Costco                                  0    0    0
  Dunnes Stores                           0    0    0
  East of England Co-operative            4    3    1
  Farmfoods                              11   16   15
  Heart of England Co-operative           0    1    0
  Heron                                  13   14   10
  Iceland                                19    9   13
  Langdale Co-operative Society           0    0    0
  Lidl                                   62   24   24
  Lincolnshire Co-operative              11    4    1
  Makro                                   0    0    0
  Marks and Spencer                      17   17   27
  Midcounties Co-operative               15   10    1
  Morrisons                             163  364  490
  Planet Organic                          0    0    0
  Sainsburys                             11   25   24
  Scottish Midland Co-operative           1    1    0
  Spar                                   60   48  102
  Tamworth Co-operative Society           0    0    0
  Tesco                                  65   47   72
  The Co-operative Group                 83   26   40
  The Radstock Co-operative Society       1    0    0
  The Southern Co-operative              10   38    5
  Waitrose                                0    0    1
  Whole Foods Market                      0    0    0

* Records with year == 2014 are stores that existed in 2014.
* Records with year >= 2015 are new stores.

# Calculate Summary Statistics
The number and area of retailer stores in each year is calculated by cumulatively summing store number and area by year, with store area approximated as the mid-value of bound store size classes and as the lower boundary of the two upper unbounded classes.

In [ ]:
# Summarise by retailer, year and size_level
store.yr <- store %>%
  count(retailer, year, size_level, sort=TRUE)

In [ ]:
# Download geolytix_retailpoints_v34_202412.csv from GitHub
url <- "https://raw.githubusercontent.com/davidmkidd/UK-Supermarket-Carbon-Emissions/refs/heads/main/geolytix_size_class.csv"
download_path <- "/content/geolytix_size_class.csv"
download.file(url, destfile = download_path, mode = "wb")

# geolytix_size_class.csv contains the area values that will be used
# for each area class when estimating retailer store area
store.size <- read.csv("/content/geolytix_size_class.csv", header=TRUE, stringsAsFactors=FALSE)
store.size

  size_level size_area_mid method
1 1           140          mid-value
2 2           840          mid-value
3 3          2100          mid-value
4 4          2800          min-value
5 5          3000          min-value

'Joining' adds the attributes from one table onto another by matching values in fields. Here, the attriributes of store.size are added to store by matching 'size_level' fields.

The dpylr join function is called *merge()*.

In [ ]:
# Join to size class attributes to store.yr
store.yr <- merge(store.yr, store.size, by = "size_level")
head(store.yr, n=2)

  size_level retailer year n    size_area_mid method
1 1          Spar     2014 1908 140           mid-value
2 1          Tesco    2014 1610 140           mid-value

Floor area of stores of each size in 2014 and new stores in subsequent years is the product of the number of stores and the size class value.

In [ ]:
# Calculate estimated store area by retailer, year, and level
store.yr$area_m2 <- store.yr$n * store.yr$size_area_mid
head(store.yr, n=2)

  size_level retailer year n    size_area_mid method    area_m2
1 1          Spar     2014 1908 140           mid-value 267120
2 1          Tesco    2014 1610 140           mid-value 225400

Cumulatively sum store number and estimated area by retailer and year.

In [ ]:
# Cumulative Sum of store number by year and retailer
store.yr.n <- store.yr  %>%
  group_by(retailer, year) %>%
  arrange(retailer, year) %>%
  summarise(sum_n = sum(n), .groups = "drop_last") %>%
  mutate(cum_sum_n = cumsum(sum_n))

In [ ]:
# Cumulative Sum of store area by year and retailer
store.yr.a <- store.yr  %>%
  group_by(retailer, year) %>%
  arrange(retailer, year) %>%
  summarise(sum_area_m2 = sum(area_m2), .groups = "drop_last") %>%
  mutate(cum_sum_area_m2 = cumsum(sum_area_m2))

In [ ]:
filter(store.yr.a, retailer == "Spar")

  retailer year sum_area_m2 cum_sum_area_m2
1 Spar     2014 267120      267120
2 Spar     2022   8400      275520
3 Spar     2023   6720      282240
4 Spar     2024  14280      296520

The cumulative sums are not calculated for years in which a retailer did not open any new stores, for example Asda in 2019.

# Reformat and Export

A 'base table' of retailer and year (2014-2024) is created to which values are added.

In [ ]:
# Create 'retailer.yr' of retailer and year 2014-2024
yr <- rep(seq(2014, 2024))
retailers <- distinct(store.yr, retailer)
retailer.yr <- expand.grid(yr, retailers$retailer)
colnames(retailer.yr)[1] <- "year"
colnames(retailer.yr)[2] <- "retailer"
retailer.yr<-data.frame(retailer.yr)

Join cumulative sum tables to retailer.yr on retailer and year fields.

In [ ]:
# Join cumulative sum tables

retailer.yr <- merge(retailer.yr, store.yr.n, by.x = c("retailer","year"), by.y = c("retailer","year"), all = TRUE)
retailer.yr <- merge(retailer.yr, store.yr.a, by.x = c("retailer","year"), by.y = c("retailer","year"), all = TRUE)


head(retailer.yr, n=7)

  retailer year sum_n cum_sum_n sum_area_m2 cum_sum_area_m2
1 Spar     2014 1908  1908      267120      267120
2 Spar     2015   NA    NA          NA          NA
3 Spar     2016   NA    NA          NA          NA
4 Spar     2017   NA    NA          NA          NA
5 Spar     2018   NA    NA          NA          NA
6 Spar     2019   NA    NA          NA          NA
7 Spar     2020   NA    NA          NA          NA

Use tidyr *fill()* to replace NAs with the value for the previous year.

In [ ]:
# Fill missing Cum Sum values
retailer.yr <- retailer.yr%>%
  arrange(retailer, year) %>%
  fill(cum_sum_n, .direction = "down")

head(retailer.yr, n=10)

   retailer year sum_n cum_sum_n sum_area_m2 cum_sum_area_m2
1  Spar     2014 1908  1908      267120      267120
2  Spar     2015   NA  1908          NA          NA
3  Spar     2016   NA  1908          NA          NA
4  Spar     2017   NA  1908          NA          NA
5  Spar     2018   NA  1908          NA          NA
6  Spar     2019   NA  1908          NA          NA
7  Spar     2020   NA  1908          NA          NA
8  Spar     2021   NA  1908          NA          NA
9  Spar     2022   60  1968        8400      275520
10 Spar     2023   48  2016        6720      282240

In [ ]:
retailer.yr<- retailer.yr %>%
  arrange(retailer, year) %>%
  fill(cum_sum_area_m2, .direction = "down")

In [ ]:
head(retailer.yr, n=2)

  retailer year sum_n cum_sum_n sum_area_m2 cum_sum_area_m2
1 Spar     2014 1908  1908      267120      267120
2 Spar     2015   NA  1908          NA      267120

In [ ]:
# Rename columns
retailer.yr <- retailer.yr %>% rename("new_store" = "sum_n",
                    "total_store" = "cum_sum_n",
                    "new_area" = "sum_area_m2",
                    "total_area" = "cum_sum_area_m2")

In [ ]:
names(retailer.yr)

[1] "retailer"    "year"        "new_store"   "total_store" "new_area"
[6] "total_area"

The final steps deal with ...

In [ ]:
# Download retailer data
url <- "https://raw.githubusercontent.com/davidmkidd/UK-Supermarket-Carbon-Emissions/refs/heads/main/retailer_data.csv"
download_path <- "/content/retailer_data.csv"
download.file(url, destfile = download_path, mode = "wb")
retailer.data <- read.csv("/content/retailer_data.csv", header=TRUE, stringsAsFactors=FALSE)

In [ ]:
# Add Retailer Code
retailer.yr <- merge(retailer.yr, retailer.data, by = "retailer", all.x = TRUE)

In [ ]:
# Set New Store and New Area which are NA to zero except for Ocardo

retailer.yr <- retailer.yr %>%
  mutate(new_store = ifelse(retailer != "Ocado" & is.na(new_store), 0, new_store)) %>%
  mutate(new_area = ifelse(retailer != "Ocado" & is.na(new_area), 0, new_area))

In [ ]:
# Set Ocado Total Store and Area to NA

retailer.yr <- retailer.yr %>%
  mutate(total_store = ifelse(retailer == "Ocado", NA, total_store)) %>%
  mutate(total_area = ifelse(retailer == "Ocado", NA, total_area))

In [ ]:
# Check
head(retailer.yr, n = 8)

  retailer year new_store total_store new_area total_area retailer_code hex
1 Spar     2014 1908      1908        267120   267120     NA            NA
2 Spar     2015    0      1908             0   267120     NA            NA
3 Spar     2016    0      1908             0   267120     NA            NA
4 Spar     2017    0      1908             0   267120     NA            NA
5 Spar     2018    0      1908             0   267120     NA            NA
6 Spar     2019    0      1908             0   267120     NA            NA
7 Spar     2020    0      1908             0   267120     NA            NA
8 Spar     2021    0      1908             0   267120     NA            NA
  revenue_2022 revenue_2023 mean_revenue cost_index
1 NA           NA           NA           NA
2 NA           NA           NA           NA
3 NA           NA           NA           NA
4 NA           NA           NA           NA
5 NA           NA           NA           NA
6 NA           NA           NA           NA
7 NA           NA           NA           NA
8 NA           NA           NA           NA

In [ ]:
retailer.yr %>%
  summarise(total_store = sum(new_store, na.rm = TRUE))

  total_store
1 18840

Export cleaned store and store.yr to csv file for next tutorial.

In [ ]:
 write.csv(store,file='/content/geolytix_retailpoints_v34_202412_clean.csv', row.names=FALSE)
 write.csv(retailer.yr,file='/content/geolytix_retailpoints_v34_202412_summary.csv', row.names=FALSE)

---

Back: [UKSmktComp Main Page](https://colab.research.google.com/drive/1f8a0pXfF9PqCujiwjf4TO4-k7ezt-6b3?usp=sharing)

Next: [Visualising Retailer Stores](https://colab.research.google.com/drive/170bNbYyXBmAjgpsRyzqzruE32Jw_5NHR#scrollTo=oUcubW-WW7ok)

---